-- nflfastR play-by-play, core columns typed (flags -> boolean). One row per (game_id, play_id).
-- Original events preserved: no_play (nullified) rows, kneels, spikes and two-point tries stay in;
-- eligibility is decided in fct_play.
select
    game_id,
    play_id,
    season,
    week,
    season_type,
    game_date::date                                          as game_date,
    home_team,
    away_team,
    posteam,
    defteam,
    qtr::integer                                             as qtr,
    game_half,
    down::integer                                            as down,
    ydstogo::integer                                         as ydstogo,
    yardline_100::integer                                    as yardline_100,
    goal_to_go = 1                                           as goal_to_go,
    quarter_seconds_remaining::integer                       as quarter_seconds_remaining,
    half_seconds_remaining::integer                          as half_seconds_remaining,
    game_seconds_remaining::integer                          as game_seconds_remaining,
    "time"                                                   as clock,
    play_type,
    play_type_nfl,
    "desc"                                                   as description,
    -- pre-play score from the offense's perspective (nflfastR: posteam_score - defteam_score before the play)
    posteam_score::integer                                   as posteam_score_pre,
    defteam_score::integer                                   as defteam_score_pre,
    score_differential::integer                              as score_differential_pre,
    -- flags
    qb_dropback = 1                                          as qb_dropback,
    pass_attempt = 1                                         as pass_attempt,      -- includes sacks (nflfastR)
    rush_attempt = 1                                         as rush_attempt,      -- includes scrambles and kneels
    sack = 1                                                 as sack,
    qb_scramble = 1                                          as qb_scramble,
    qb_kneel = 1                                             as qb_kneel,
    qb_spike = 1                                             as qb_spike,
    two_point_attempt = 1                                    as two_point_attempt,
    two_point_conv_result,
    complete_pass = 1                                        as complete_pass,
    incomplete_pass = 1                                      as incomplete_pass,
    interception = 1                                         as interception,
    penalty = 1                                              as penalty,
    penalty_type,
    penalty_team,
    aborted_play = 1                                         as aborted_play,
    play_deleted = 1                                         as play_deleted,
    special_teams_play = 1                                   as special_teams_play,
    shotgun = 1                                              as shotgun,
    no_huddle = 1                                            as no_huddle,
    touchdown = 1                                            as touchdown,
    pass_touchdown = 1                                       as pass_touchdown,
    rush_touchdown = 1                                       as rush_touchdown,
    first_down = 1                                           as first_down,
    fumble = 1                                               as fumble,
    fumble_lost = 1                                          as fumble_lost,
    success = 1                                              as success,
    -- actors
    passer_player_id,
    passer_player_name,
    receiver_player_id,
    receiver_player_name,
    rusher_player_id,
    rusher_player_name,
    kicker_player_id,
    td_player_id,
    interception_player_id,
    -- yards and depth
    air_yards::numeric                                       as air_yards,
    yards_after_catch::numeric                               as yards_after_catch,
    yards_gained::numeric                                    as yards_gained,
    passing_yards::numeric                                   as passing_yards,
    receiving_yards::numeric                                 as receiving_yards,
    rushing_yards::numeric                                   as rushing_yards,
    pass_location,
    pass_length,
    run_location,
    run_gap,
    -- models
    epa::numeric                                             as epa,
    wpa::numeric                                             as wpa,
    wp::numeric                                              as wp_pre,
    cp::numeric                                              as completion_probability,
    cpoe::numeric                                            as cpoe,
    xpass::numeric                                           as xpass,
    pass_oe::numeric                                         as pass_oe,
    -- drive / series
    drive::integer                                           as drive,
    fixed_drive::integer                                     as fixed_drive,
    series::integer                                          as series,
    _fetched_at                                              as source_fetched_at
from {{ source('raw', 'nfl_pbp') }}
where season >= {{ var('seasons_start') }}
