select
    gsis_id,
    display_name,
    first_name,
    last_name,
    short_name,
    position,
    position_group,
    latest_team,
    status,
    birth_date::date                       as birth_date,
    height,
    weight,
    college_name,
    rookie_season,
    last_season,
    years_of_experience,
    draft_year,
    draft_round,
    draft_pick,
    draft_team,
    headshot                               as headshot_url,
    pfr_id,
    esb_id,
    espn_id,
    nfl_id,
    pff_id,
    _fetched_at                            as source_fetched_at
from {{ source('raw', 'nfl_players') }}
